First version for certificate generation
calculquebec/CQORC pull request #77
Opened 2024-02-23 13:48 UTC by hgingras

2024-04-02 18:33 UTC, ccoulombe requested changes

2024-04-02 18:33 UTC, ccoulombe commented on email_template/email_certificates_FR.yml
Remplacer `certification` par `attestation de participation`.

2024-04-02 18:33 UTC, ccoulombe commented on Attestation_template/attestation_template_sample_english_logo.svg
Corriger le titre `Ceritificate` -> `Attestation`

2024-04-02 18:33 UTC, ccoulombe commented on create_certificate.py
> +        send_email(eb_event, attended_guest_test, args.email_tplt_dir, args.send_self, args.number_to_send, args.language, args.gmail_user, args.gmail_password, args.self_email, attach_certificate=Tr
`attended_guest_test` n'existe pas

2024-04-02 18:59 UTC, hgingras commented on email_template/email_certificates_FR.yml
Okay

2024-04-02 19:13 UTC, hgingras commented on Attestation_template/attestation_template_sample_english_logo.svg
Okay

2024-04-02 19:14 UTC, hgingras commented on create_certificate.py
> +        send_email(eb_event, attended_guest_test, args.email_tplt_dir, args.send_self, args.number_to_send, args.language, args.gmail_user, args.gmail_password, args.self_email, attach_certificate=Tr
J'ai oublié de changer le nom de la variable. J'ai fait la correction.

2024-08-22 19:06 UTC, mboisson commented
Il faudrait déplacer les templates et les adresses hardcodées de Calcul Québec dans un dépôt privé, plutôt que dans ce dépôt.

2025-07-16 20:03 UTC, hgingras commented
> > Il faudrait déplacer les templates et les adresses hardcodées de Calcul Québec dans un dépôt privé, plutôt que dans ce dépôt.
> 
> C'est où que tu me suggères de transférer les templates?

J'ai trouvé.

2025-07-16 20:38 UTC, mboisson commented
dans le dépôt de secrets

2025-07-29 16:39 UTC, merged